import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'blogPost',
  title: '📝 Blog Posts',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'seo', title: 'SEO' },
    { name: 'products', title: 'Products' },
    { name: 'source', title: 'Source' },
  ],
  fields: [
    // Content Group
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'content',
      options: {
        list: [
          { title: '💄 Makeup', value: 'makeup' },
          { title: '🧴 Skincare', value: 'skincare' },
          { title: '👗 Fashion', value: 'fashion' },
          { title: '✨ Lifestyle', value: 'lifestyle' },
          { title: '✈️ Travel', value: 'travel' },
        ],
      },
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      group: 'content',
      rows: 2,
      description: 'Short preview shown on blog cards',
    }),
    defineField({
      name: 'content',
      title: 'Full Content',
      type: 'array',
      group: 'content',
      of: [
        { type: 'block' },
        { type: 'image' },
      ],
    }),
    defineField({
      name: 'thumbnail',
      title: 'Thumbnail Image',
      type: 'image',
      group: 'content',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'content',
      options: {
        list: [
          { title: '📝 Draft - Needs Review', value: 'draft' },
          { title: '✅ Published', value: 'published' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft',
    }),
    
    // SEO Group
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      group: 'seo',
      description: 'Title for search engines (60 chars max)',
      validation: Rule => Rule.max(60),
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      group: 'seo',
      rows: 2,
      description: 'Description for search engines (155 chars max)',
      validation: Rule => Rule.max(155),
    }),
    defineField({
      name: 'suggestedTags',
      title: 'Tags',
      type: 'array',
      group: 'seo',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
    }),
    
    // Products Group
    defineField({
      name: 'productLinks',
      title: 'Product Links',
      type: 'array',
      group: 'products',
      description: 'Products mentioned in this post',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'name', title: 'Product Name', type: 'string' },
            { name: 'brand', title: 'Brand', type: 'string' },
            { name: 'amazonUrl', title: 'Amazon Link', type: 'url' },
            { name: 'shopmyUrl', title: 'ShopMy Link', type: 'url' },
            { name: 'needsShopmy', title: 'Needs ShopMy Link', type: 'boolean' },
          ],
          preview: {
            select: {
              title: 'name',
              brand: 'brand',
              needsShopmy: 'needsShopmy',
            },
            prepare({ title, brand, needsShopmy }) {
              return {
                title: `${brand} - ${title}`,
                subtitle: needsShopmy ? '⚠️ Needs ShopMy link' : '✓ Links ready',
              }
            },
          },
        },
      ],
    }),
    
    // Source Group
    defineField({
      name: 'platform',
      title: 'Source Platform',
      type: 'string',
      group: 'source',
      options: {
        list: [
          { title: '📺 YouTube', value: 'youtube' },
          { title: '🎵 TikTok', value: 'tiktok' },
          { title: '📸 Instagram', value: 'instagram' },
          { title: '✍️ Original', value: 'original' },
        ],
      },
      readOnly: true,
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video URL',
      type: 'url',
      group: 'source',
    }),
    defineField({
      name: 'videoId',
      title: 'Video ID',
      type: 'string',
      group: 'source',
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: 'views',
      title: 'View Count',
      type: 'string',
      group: 'source',
    }),
    defineField({
      name: 'autoGenerated',
      title: 'Auto-Generated',
      type: 'boolean',
      group: 'source',
      readOnly: true,
      description: 'This post was automatically created by the content engine',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Publish Date',
      type: 'datetime',
      group: 'content',
    }),
  ],
  orderings: [
    {
      title: 'Publish Date, New',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
    {
      title: 'Drafts First',
      name: 'draftsFirst',
      by: [{ field: 'status', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      category: 'category',
      status: 'status',
      media: 'thumbnail',
      autoGenerated: 'autoGenerated',
    },
    prepare({ title, category, status, media, autoGenerated }) {
      const statusEmoji = status === 'published' ? '✅' : '📝'
      const autoEmoji = autoGenerated ? '🤖 ' : ''
      return {
        title: `${statusEmoji} ${autoEmoji}${title}`,
        subtitle: category,
        media,
      }
    },
  },
})
