// Sanity CMS Service
// Creates draft blog posts from analyzed content

import { createClient } from '@sanity/client'

let client = null

export function initSanity(projectId, dataset, token) {
  client = createClient({
    projectId,
    dataset,
    token,
    apiVersion: '2024-01-01',
    useCdn: false
  })
}

export async function checkIfVideoProcessed(videoId) {
  if (!client) throw new Error('Sanity client not initialized')
  
  const query = `*[_type == "blogPost" && videoId == $videoId][0]`
  const result = await client.fetch(query, { videoId })
  return !!result
}

// Download image and upload to Sanity
async function uploadImageFromUrl(imageUrl, filename) {
  if (!imageUrl || !client) return null
  
  try {
    console.log(`      Downloading thumbnail from YouTube...`)
    
    // Fetch the image
    const response = await fetch(imageUrl)
    if (!response.ok) {
      console.log(`      Failed to fetch image: ${response.status}`)
      return null
    }
    
    // Get the image as a buffer
    const arrayBuffer = await response.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)
    
    // Upload to Sanity
    console.log(`      Uploading thumbnail to Sanity...`)
    const asset = await client.assets.upload('image', buffer, {
      filename: filename || 'thumbnail.jpg',
      contentType: 'image/jpeg'
    })
    
    console.log(`      ✓ Thumbnail uploaded: ${asset._id}`)
    
    return {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: asset._id
      }
    }
  } catch (error) {
    console.error(`      Failed to upload thumbnail:`, error.message)
    return null
  }
}

export async function createDraftBlogPost({
  video,
  analysis,
  productLinks
}) {
  if (!client) throw new Error('Sanity client not initialized')
  
  // Build the content with product links inserted
  let content = analysis.blogContent || ''
  
  // Replace product placeholders with actual links
  for (const productLink of productLinks) {
    const placeholder = `[PRODUCT_LINK:${productLink.name}]`
    let linkHtml = ''
    
    if (productLink.shopmyUrl) {
      linkHtml = `**[${productLink.name}](${productLink.shopmyUrl})** (ShopMy)`
    } else if (productLink.amazonUrl) {
      linkHtml = `**[${productLink.name}](${productLink.amazonUrl})** (Amazon)`
    } else {
      linkHtml = `**${productLink.name}**`
    }
    
    content = content.replace(placeholder, linkHtml)
  }
  
  // Upload YouTube thumbnail to Sanity
  let thumbnailAsset = null
  if (video.thumbnail) {
    const filename = `${video.id}-thumbnail.jpg`
    thumbnailAsset = await uploadImageFromUrl(video.thumbnail, filename)
  }
  
  // Create the blog post document
  const doc = {
    _type: 'blogPost',
    title: analysis.blogTitle,
    slug: {
      _type: 'slug',
      current: generateSlug(analysis.blogTitle)
    },
    seoTitle: analysis.seoTitle,
    seoDescription: analysis.seoDescription,
    excerpt: analysis.blogExcerpt,
    category: analysis.category?.toLowerCase() || 'lifestyle',
    platform: video.platform?.toLowerCase() || 'youtube',
    videoUrl: video.url,
    videoId: video.id,
    // Save as actual Sanity image asset
    thumbnail: thumbnailAsset,
    // Also keep URL as backup
    thumbnailUrl: video.thumbnail || null,
    views: video.viewCount ? `${formatViews(video.viewCount)} views` : undefined,
    content: [
      {
        _type: 'block',
        _key: generateKey(),
        style: 'normal',
        markDefs: [],
        children: [
          {
            _type: 'span',
            _key: generateKey(),
            text: content,
            marks: []
          }
        ]
      }
    ],
    // Store product info for reference
    productLinks: productLinks.map(p => ({
      _type: 'object',
      _key: generateKey(),
      name: p.name,
      brand: p.brand,
      amazonUrl: p.amazonUrl || null,
      shopmyUrl: p.shopmyUrl || null,
      needsShopmy: !p.shopmyUrl
    })),
    suggestedTags: analysis.suggestedTags || [],
    status: 'draft', // Always create as draft for Kyndall to review
    publishedAt: new Date().toISOString(),
    autoGenerated: true,
    sourceVideo: {
      id: video.id,
      title: video.title,
      platform: video.platform,
      publishedAt: video.publishedAt
    }
  }
  
  const result = await client.create(doc)
  return result
}

export async function getRecentDrafts(limit = 10) {
  if (!client) throw new Error('Sanity client not initialized')
  
  const query = `*[_type == "blogPost" && status == "draft" && autoGenerated == true] | order(publishedAt desc)[0...$limit] {
    _id,
    title,
    category,
    platform,
    publishedAt,
    productLinks
  }`
  
  return client.fetch(query, { limit })
}

function generateSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 96)
}

function generateKey() {
  return Math.random().toString(36).substring(2, 10)
}

function formatViews(count) {
  const num = parseInt(count)
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(0)}K`
  return num.toString()
}
